version: '3.7'
services:

  jupyter:
    image: jupyter
    container_name: jupyter
    restart: unless-stopped
    command: jupyter-notebook --ip=0.0.0.0 --no-browser
    ports:
      - "8888:8888"
    volumes:
      - ./shared/:/home/app/shared/